apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
    - port: 80
      protocol: TCP
      name: auth-service
      targetPort: 8080
