apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
    - port: 80
      protocol: TCP
      name: book-service
      targetPort: 8080
